name: liquid_flutter_test_utils
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  golden_toolkit: ^0.15.0
  go_router: ^2.0.0
  liquid_flutter: ^18.2.0
  liquid_flutter_emd_theme: ^0.0.2
  mtrust_better_log: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: packages/liquid_flutter/fonts/Lato-Regular.ttf
          weight: 500
        - asset: packages/liquid_flutter/fonts/Lato-Bold.ttf
          weight: 800
    - family: EMD
      fonts:
        - asset: packages/liquid_flutter_emd_theme/fonts/EMD.ttf
    - family: LiquidIcons
      fonts:
        - asset: packages/liquid_flutter_emd_theme/fonts/LiquidIcons.ttf