name: liquid_flutter_test_utils
description: Test utilities for Liquid Flutter and more
version: 1.4.1
homepage: https://github.com/emdgroup-liquid/liquid-flutter-test-utils
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"
dependencies:
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  go_router: ^14.8.1
  liquid_flutter: ">=19.4.0 <22.0.0"
  mtrust_better_log: ^1.0.0
  path: ^1.9.0
  flutter_svg: ^2.0.17
  responsive_builder: ^0.7.1
dev_dependencies:
  flutter_lints: ^5.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: packages/liquid_flutter/fonts/Lato-Regular.ttf
          weight: 500
        - asset: packages/liquid_flutter/fonts/Lato-Bold.ttf
          weight: 800
dependency_overrides:
  liquid_flutter: 21.0.5
